name: google_mediapipe_face_detection_web
description: "A flutter plugin that implements Google's MediaPipe Face Detection for Web Platform"
version: 0.0.1
homepage: https://khushal-rao.web.app
repository: https://github.com/TecHaxter/google_mediapipe_face_detection
publish_to: "none"

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.7.1
  js: ^0.6.3
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.0
  google_mediapipe_face_detection_platform_interface:
    path: ../google_mediapipe_face_detection_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: google_mediapipe_face_detection
    platforms:
      web:
        pluginClass: GoogleMediapipeFaceDetectionWeb
        fileName: google_mediapipe_face_detection_web.dart
