name: google_mediapipe_face_detection
description: "A flutter plugin that implements Google's MediaPipe Face Detection"
version: 0.0.1
homepage: https://khushal-rao.web.app
repository: https://github.com/TecHaxter/google_mediapipe_face_detection

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mlkit_commons: ^0.6.0
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      # android:
      #   package: com.khushal.google_mediapipe_face_detection
      #   pluginClass: GoogleMediapipeFaceDetectionPlugin
      # ios:
      #   pluginClass: GoogleMediapipeFaceDetectionPlugin
      web:
        pluginClass: GoogleMediaPipeFaceDetectionMultiPlatform
        fileName: multi-platform/web/google_mediapipe_face_detection_web.dart
