name: google_mediapipe_face_detection_platform_interface
description: "A flutter plugin that implements Google's MediaPipe Face Detection Platform Interface"
version: 0.0.1
homepage: https://khushal-rao.web.app
repository: https://github.com/TecHaxter/google_mediapipe_face_detection
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.7.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - google_mediapipe_face_detection
